// Tiny audio helper. Voice clips live in public/audio/ and are generated by
// scripts/generate-audio.mjs; playUrl() plays any other resolved asset (e.g.
// a Vite-imported file from src/assets/, like the Kraken's background sting).
// Everything degrades to silence if a file is missing or the browser blocks
// playback.

const BASE = import.meta.env.BASE_URL;
const cache = new Map<string, HTMLAudioElement>();

function element(src: string): HTMLAudioElement {
  let el = cache.get(src);
  if (!el) {
    el = new Audio(src);
    el.preload = "auto";
    cache.set(src, el);
  }
  return el;
}

function play(src: string, volume?: number): Promise<void> {
  const el = element(src);
  if (volume !== undefined) el.volume = volume;
  try {
    el.currentTime = 0;
  } catch {
    // not seekable yet — ignore
  }
  const result = el.play() as Promise<void> | undefined;
  return result instanceof Promise ? result.catch(() => undefined) : Promise.resolve();
}

function promptSrc(word: string): string {
  return `${BASE}audio/prompt-${word.toLowerCase()}.mp3`;
}

/** Speak "Which one spells <word>?" */
export function playPrompt(word: string): Promise<void> {
  return play(promptSrc(word));
}

/** Play a named cue clip from public/audio/: correct | wrong | defeat-3 | ... */
export function playCue(name: string): Promise<void> {
  return play(`${BASE}audio/${name}.mp3`);
}

/** Play an arbitrary resolved asset URL (e.g. a Vite-imported file), optionally at a lower volume. */
export function playUrl(url: string, volume?: number): Promise<void> {
  return play(url, volume);
}

/** Warm the cache from a user gesture so the first prompt starts instantly. */
export function preloadPrompts(words: string[]): void {
  for (const w of words) element(promptSrc(w));
}
