// Tiny audio helper. Clips live in public/audio/ and are generated by
// scripts/generate-audio.mjs. Everything degrades to silence if a file is
// missing or the browser blocks playback.

const BASE = import.meta.env.BASE_URL;
const cache = new Map<string, HTMLAudioElement>();

function element(src: string): HTMLAudioElement {
  let el = cache.get(src);
  if (!el) {
    el = new Audio(src);
    el.preload = "auto";
    cache.set(src, el);
  }
  return el;
}

function play(src: string): Promise<void> {
  const el = element(src);
  try {
    el.currentTime = 0;
  } catch {
    // not seekable yet — ignore
  }
  const result = el.play() as Promise<void> | undefined;
  return result instanceof Promise ? result.catch(() => undefined) : Promise.resolve();
}

function promptSrc(word: string): string {
  return `${BASE}audio/prompt-${word.toLowerCase()}.mp3`;
}

/** Speak "Which one spells <word>?" */
export function playPrompt(word: string): Promise<void> {
  return play(promptSrc(word));
}

/** Play a named cue clip: correct | wrong | defeat | survive-barely | ... */
export function playCue(name: string): Promise<void> {
  return play(`${BASE}audio/${name}.mp3`);
}

/** Warm the cache from a user gesture so the first prompt starts instantly. */
export function preloadPrompts(words: string[]): void {
  for (const w of words) element(promptSrc(w));
}
