// Tiny audio helper. Voice clips live in public/audio/ and are generated by
// scripts/generate-audio.mjs; playUrl() plays any other resolved asset (e.g.
// a Vite-imported file from src/assets/, like the Kraken's background sting).
// Everything degrades to silence if a file is missing or the browser blocks
// playback.

const BASE = import.meta.env.BASE_URL;
const cache = new Map<string, HTMLAudioElement>();

function element(src: string): HTMLAudioElement {
  let el = cache.get(src);
  if (!el) {
    el = new Audio(src);
    el.preload = "auto";
    cache.set(src, el);
  }
  return el;
}

function play(src: string, volume?: number): Promise<void> {
  const el = element(src);
  // Elements are cached by src (see element() above), so a previous call's
  // volume (e.g. kraken-music.wav's 0.55) would otherwise stick around for
  // every later play() of that same src that doesn't pass one explicitly.
  el.volume = volume ?? 1;
  try {
    el.currentTime = 0;
  } catch {
    // not seekable yet — ignore
  }
  const result = el.play() as Promise<void> | undefined;
  return result instanceof Promise ? result.catch(() => undefined) : Promise.resolve();
}

function promptSrc(word: string): string {
  return `${BASE}audio/prompt-${word.toLowerCase()}.mp3`;
}

/** Speak "Which one spells <word>?" */
export function playPrompt(word: string): Promise<void> {
  return play(promptSrc(word));
}

/** Play a named cue clip from public/audio/: correct | wrong | defeat-3 | ... */
export function playCue(name: string): Promise<void> {
  return play(`${BASE}audio/${name}.mp3`);
}

/** Play an arbitrary resolved asset URL (e.g. a Vite-imported file), optionally at a lower volume. */
export function playUrl(url: string, volume?: number): Promise<void> {
  return play(url, volume);
}

/** Warm the cache from a user gesture so the first prompt starts instantly. */
export function preloadPrompts(words: string[]): void {
  for (const w of words) element(promptSrc(w));
}

// Background music: one looping element, separate from the one-shot cache
// above (play() rewinds and resets volume on every call, which is exactly
// wrong for a track that should keep going across rounds).
let music: HTMLAudioElement | null = null;

function ensureMusicElement(url: string): HTMLAudioElement {
  if (!music || music.getAttribute("src") !== url) {
    music?.pause();
    music = new Audio(url);
    music.loop = true;
    music.preload = "auto";
  }
  return music;
}

/**
 * Warm the browser's fetch of the background track ahead of time, so
 * playback can start instantly once a boss round begins instead of a cold
 * fetch of a multi-MB file starting right when it's meant to be heard.
 * Only sets up the element/starts the network request -- doesn't call
 * play(), so (unlike startMusic) it's safe to call with no user gesture,
 * e.g. once on app mount.
 */
export function preloadMusic(url: string): void {
  ensureMusicElement(url);
}

/** Start (or resume) the looping background track. Safe to call repeatedly. */
export function startMusic(url: string, volume: number): Promise<void> {
  const el = ensureMusicElement(url);
  el.volume = volume;
  const result = el.play() as Promise<void> | undefined;
  return result instanceof Promise ? result.catch(() => undefined) : Promise.resolve();
}

/** Pause the track where it is (mute), so unmuting picks up mid-song. */
export function pauseMusic(): void {
  music?.pause();
}

/** Pause and rewind, so the next game starts the track from the top. */
export function stopMusic(): void {
  if (!music) return;
  music.pause();
  try {
    music.currentTime = 0;
  } catch {
    // not seekable yet -- ignore
  }
}
